PARAMS:
  TOKEN:
    CLIENT_ID: None
    ACCESS_TOKEN: None
    REFRESH_TOKEN: None
    CLIENT_SECRET: None

  DATABASE:
    HOST: None
    DATABASE: None
    USER: None
    PASSWORD: None

  ELASTICSEARCH:
    HOST: None
    PORT: None
    USER: None
    PASSWORD: None